resource "aws_instance" "my_instance" {
  ami           = "ami-0c55b159cbfafe1f0" 
  instance_type = "t2.micro"  

  key_name = aws_key_pair.ec2_key.key_name 
  security_groups = [aws_security_group.ec2_sg.name]  

  tags = {
    Name = "MyEC2Instance"
  }

  # user_data = <<-EOF
  #   #!/bin/bash
  #   echo "Hello, World!" > /var/www/html/index.html
  # EOF
}

output "instance_public_ip" {
  value = aws_instance.my_instance.public_ip
}
